Add files via upload

diff --git a/postBuild b/postBuild
--- a/postBuild
+++ b/postBuild
@@ -1,2 +1,5 @@
 #!/bin/bash
-pip install ga4gh.vrs[extras]
+set -e  # don't allow errors to fail silently
+echo `which pip`  # in case the wrong `pip` is used, this will let us debug
+pip install -e ga4gh.vrs[extras] # install the custom library
+
